/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import dao.KhachHangDAO;
import dao.LoaiXeDAO;
import dao.MauXeDAO;
import dao.XeDAO;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import obj.KhachHang;
import obj.LoaiXe;
import obj.MauXe;
import obj.Xe;

/**
 *
 * @author phamq
 */
public class Form_Xe extends javax.swing.JPanel {
    private ArrayList<MauXe> listMauXe;
    private ArrayList<Xe> listXe;
    ArrayList<LoaiXe> listTenLoaiXe;
    DefaultTableModel modelXe;
    DefaultTableModel modelMauXe;
    MauXeDAO mauXeDAO;
    LoaiXeDAO loaiXeDAO;
    XeDAO xeDAO = new XeDAO();
    /**
     * Creates new form Form_Xe
     */
    public Form_Xe() {
        initComponents();
        setComBoModel();
    
  
        showlistMauXe();
     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog_ThemMauXe = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton_themxe_luu = new javax.swing.JButton();
        jButton_themxe_huy_ = new javax.swing.JButton();
        jTextField_themXe_soluong = new javax.swing.JTextField();
        jTextField_themxe_gia = new javax.swing.JTextField();
        jTextField_themxe_nuocsx = new javax.swing.JTextField();
        jTextField_themxe_mausac = new javax.swing.JTextField();
        jTextField_themXe_tenxe = new javax.swing.JTextField();
        jComboBox_LoaiXe = new javax.swing.JComboBox<>();
        jDialog_SuaXe = new javax.swing.JDialog();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButton_themxe_luu1 = new javax.swing.JButton();
        jButton_suaxe_huy_ = new javax.swing.JButton();
        jTextField_suaxe_somay = new javax.swing.JTextField();
        jTextField_suaxe_sokhung = new javax.swing.JTextField();
        jTextField_suaXe_soluong = new javax.swing.JTextField();
        jTextField_suaxe_gia = new javax.swing.JTextField();
        jTextField_suaxe_nuocsx = new javax.swing.JTextField();
        jTextField_suaxe_mausac = new javax.swing.JTextField();
        jTextField_suaxe_loaixe = new javax.swing.JTextField();
        jTextField_suaXe_tenxe = new javax.swing.JTextField();
        jDialog_ThemChiTietXe = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextField_themChiTietXe_SoKhung = new javax.swing.JTextField();
        jComboBox_TenXe = new javax.swing.JComboBox<>();
        jTextField_themChiTietXe_SoMay = new javax.swing.JTextField();
        jButton_themChiTietXe_luu = new javax.swing.JButton();
        jButton_themChiTietXe_huy = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_mauSac = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_tim_xe_ = new javax.swing.JTextField();
        jButton_tim_xe_ = new javax.swing.JButton();
        jButton_xoa_xe_ = new javax.swing.JButton();
        jButton_sua_xe_ = new javax.swing.JButton();
        jButton_them_chitietxe_ = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_ds_ChitietXe = new javax.swing.JTable();
        jButton_them_mauxe_ = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_dsMauXe = new javax.swing.JTable();

        jLabel10.setText("Tên Xe :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Thêm Mẫu Xe");

        jLabel12.setText("Nước Sản Xuất :");

        jLabel13.setText("Loại Xe :");

        jLabel14.setText("Màu Sắc :");

        jLabel15.setText("Giá :");

        jLabel16.setText("Số Lượng :");

        jButton_themxe_luu.setText("Lưu");
        jButton_themxe_luu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_themxe_luuMouseClicked(evt);
            }
        });

        jButton_themxe_huy_.setText("Huỷ");
        jButton_themxe_huy_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_themxe_huy_MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jDialog_ThemMauXeLayout = new javax.swing.GroupLayout(jDialog_ThemMauXe.getContentPane());
        jDialog_ThemMauXe.getContentPane().setLayout(jDialog_ThemMauXeLayout);
        jDialog_ThemMauXeLayout.setHorizontalGroup(
            jDialog_ThemMauXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_ThemMauXeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jDialog_ThemMauXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jDialog_ThemMauXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField_themXe_tenxe, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_themxe_mausac, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_themxe_nuocsx, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_themxe_gia, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_themXe_soluong, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox_LoaiXe, 0, 130, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jDialog_ThemMauXeLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jButton_themxe_luu, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jButton_themxe_huy_, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog_ThemMauXeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(50, 50, 50))
        );
        jDialog_ThemMauXeLayout.setVerticalGroup(
            jDialog_ThemMauXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_ThemMauXeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog_ThemMauXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_themXe_tenxe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog_ThemMauXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_LoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog_ThemMauXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_themxe_mausac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog_ThemMauXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_themxe_nuocsx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog_ThemMauXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_themxe_gia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog_ThemMauXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_themXe_soluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog_ThemMauXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_themxe_luu)
                    .addComponent(jButton_themxe_huy_))
                .addGap(18, 18, 18))
        );

        jDialog_SuaXe.setMinimumSize(new java.awt.Dimension(273, 368));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setText("Sửa Xe");

        jLabel20.setText("Tên Xe :");

        jLabel21.setText("Loại Xe :");

        jLabel22.setText("Màu Sắc :");

        jLabel23.setText("Nước Sản Xuất :");

        jLabel24.setText("Giá :");

        jLabel25.setText("Số Lượng :");

        jLabel26.setText("Số Khung :");

        jLabel27.setText("Số Máy :");

        jButton_themxe_luu1.setText("Lưu");

        jButton_suaxe_huy_.setText("Huỷ");
        jButton_suaxe_huy_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_suaxe_huy_MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jDialog_SuaXeLayout = new javax.swing.GroupLayout(jDialog_SuaXe.getContentPane());
        jDialog_SuaXe.getContentPane().setLayout(jDialog_SuaXeLayout);
        jDialog_SuaXeLayout.setHorizontalGroup(
            jDialog_SuaXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_SuaXeLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jDialog_SuaXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog_SuaXeLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButton_themxe_luu1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jButton_suaxe_huy_, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog_SuaXeLayout.createSequentialGroup()
                        .addGroup(jDialog_SuaXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jDialog_SuaXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField_suaxe_sokhung, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_suaXe_tenxe, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_suaxe_loaixe, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_suaxe_mausac, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_suaxe_nuocsx, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_suaxe_gia, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_suaXe_soluong, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_suaxe_somay, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jDialog_SuaXeLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel19)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDialog_SuaXeLayout.setVerticalGroup(
            jDialog_SuaXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_SuaXeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog_SuaXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_suaXe_tenxe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog_SuaXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_suaxe_loaixe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog_SuaXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_suaxe_mausac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog_SuaXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_suaxe_nuocsx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog_SuaXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_suaxe_gia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog_SuaXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_suaXe_soluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog_SuaXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_suaxe_sokhung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog_SuaXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_suaxe_somay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog_SuaXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_themxe_luu1)
                    .addComponent(jButton_suaxe_huy_))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setText("Thêm Chi Tiết Xe");

        jLabel18.setText("Tên Xe :");

        jLabel28.setText("Số Khung :");

        jLabel29.setText("Số Máy :");

        jComboBox_TenXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_TenXeActionPerformed(evt);
            }
        });

        jButton_themChiTietXe_luu.setText("Lưu");
        jButton_themChiTietXe_luu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_themChiTietXe_luuMouseClicked(evt);
            }
        });

        jButton_themChiTietXe_huy.setText("Huỷ");
        jButton_themChiTietXe_huy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_themChiTietXe_huyMouseClicked(evt);
            }
        });

        jLabel2.setText("Màu :");

        javax.swing.GroupLayout jDialog_ThemChiTietXeLayout = new javax.swing.GroupLayout(jDialog_ThemChiTietXe.getContentPane());
        jDialog_ThemChiTietXe.getContentPane().setLayout(jDialog_ThemChiTietXeLayout);
        jDialog_ThemChiTietXeLayout.setHorizontalGroup(
            jDialog_ThemChiTietXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_ThemChiTietXeLayout.createSequentialGroup()
                .addGroup(jDialog_ThemChiTietXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog_ThemChiTietXeLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel17))
                    .addGroup(jDialog_ThemChiTietXeLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jDialog_ThemChiTietXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialog_ThemChiTietXeLayout.createSequentialGroup()
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_themChiTietXe_SoKhung, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDialog_ThemChiTietXeLayout.createSequentialGroup()
                                .addGroup(jDialog_ThemChiTietXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                                .addGroup(jDialog_ThemChiTietXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDialog_ThemChiTietXeLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField_themChiTietXe_SoMay, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jDialog_ThemChiTietXeLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jDialog_ThemChiTietXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jComboBox_TenXe, 0, 225, Short.MAX_VALUE)
                                            .addComponent(jComboBox_mauSac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))))
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(jDialog_ThemChiTietXeLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jButton_themChiTietXe_luu, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_themChiTietXe_huy, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        jDialog_ThemChiTietXeLayout.setVerticalGroup(
            jDialog_ThemChiTietXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_ThemChiTietXeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog_ThemChiTietXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_TenXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog_ThemChiTietXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_mauSac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog_ThemChiTietXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_themChiTietXe_SoKhung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog_ThemChiTietXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_themChiTietXe_SoMay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog_ThemChiTietXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_themChiTietXe_luu)
                    .addComponent(jButton_themChiTietXe_huy))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Danh Sách Xe");

        jButton_tim_xe_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_search_24px.png"))); // NOI18N
        jButton_tim_xe_.setText("Tìm Kiếm");

        jButton_xoa_xe_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_delete_sign_24px_1.png"))); // NOI18N
        jButton_xoa_xe_.setText("Xoá Xe");
        jButton_xoa_xe_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_xoa_xe_MouseClicked(evt);
            }
        });

        jButton_sua_xe_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_edit_calendar_24px.png"))); // NOI18N
        jButton_sua_xe_.setText("Cập Nhật");
        jButton_sua_xe_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_sua_xe_MouseClicked(evt);
            }
        });

        jButton_them_chitietxe_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_add_24px.png"))); // NOI18N
        jButton_them_chitietxe_.setText("Thêm Chi Tiết Xe");
        jButton_them_chitietxe_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_them_chitietxe_MouseClicked(evt);
            }
        });

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh Sách Chi Tiết Xe"));

        jTable_ds_ChitietXe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable_ds_ChitietXe);

        jButton_them_mauxe_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_add_24px.png"))); // NOI18N
        jButton_them_mauxe_.setText("Thêm Mẫu Xe");
        jButton_them_mauxe_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_them_mauxe_MouseClicked(evt);
            }
        });

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh Sách Mẫu Xe"));

        jTable_dsMauXe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_dsMauXe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_dsMauXeMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable_dsMauXe);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_tim_xe_, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_tim_xe_))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 236, Short.MAX_VALUE)
                        .addComponent(jButton_them_mauxe_)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_them_chitietxe_)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_sua_xe_)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_xoa_xe_)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_tim_xe_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_tim_xe_, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_xoa_xe_)
                    .addComponent(jButton_sua_xe_)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_them_chitietxe_)
                        .addComponent(jButton_them_mauxe_)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 736, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_sua_xe_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_sua_xe_MouseClicked

        jDialog_SuaXe.setVisible(true);
        jDialog_SuaXe.pack();
        jDialog_SuaXe.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        jDialog_SuaXe.setResizable(false);
        jDialog_SuaXe.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton_sua_xe_MouseClicked

    private void jButton_them_chitietxe_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_them_chitietxe_MouseClicked
       
        jDialog_ThemChiTietXe.setVisible(true);
        jDialog_ThemChiTietXe.pack();
        jDialog_ThemChiTietXe.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        jDialog_ThemChiTietXe.setResizable(false);
        jDialog_ThemChiTietXe.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton_them_chitietxe_MouseClicked

    private void jButton_themxe_huy_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_themxe_huy_MouseClicked
        // TODO add your handling code here:
        jDialog_ThemMauXe.setVisible(false);
    }//GEN-LAST:event_jButton_themxe_huy_MouseClicked

    private void jButton_suaxe_huy_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_suaxe_huy_MouseClicked
        // TODO add your handling code here:
        jDialog_ThemChiTietXe.setVisible(false);
    }//GEN-LAST:event_jButton_suaxe_huy_MouseClicked

    private void jButton_themChiTietXe_huyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_themChiTietXe_huyMouseClicked
        // TODO add your handling code here:
        jDialog_ThemChiTietXe.setVisible(false);
    }//GEN-LAST:event_jButton_themChiTietXe_huyMouseClicked

    private void jButton_them_mauxe_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_them_mauxe_MouseClicked
        // TODO add your handling code here:
        jDialog_ThemMauXe.setVisible(true);
        jDialog_ThemMauXe.pack();
        jDialog_ThemMauXe.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        jDialog_ThemMauXe.setResizable(false);
        jDialog_ThemMauXe.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton_them_mauxe_MouseClicked

    private void jButton_themxe_luuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_themxe_luuMouseClicked
        // TODO add your handling code here:
        String tenXe = jTextField_themXe_tenxe.getText();
        BigDecimal gia =  new BigDecimal(jTextField_themxe_gia.getText());
        int soLuong = Integer.parseInt(jTextField_themXe_soluong.getText());
        String mauSac = jTextField_themxe_mausac.getText();
        String nuocSX = jTextField_themxe_nuocsx.getText();
        
        String tenloaixe = jComboBox_LoaiXe.getSelectedItem().toString();
        loaiXeDAO= new LoaiXeDAO();
        LoaiXe loaiXe = loaiXeDAO.getLoaiXeByName(tenloaixe); 
        int maLoaiXe = loaiXe.getMaLoaiXe();
        
        MauXe mauxe = new MauXe();
        mauxe.setTenMauXe(tenXe);
        mauxe.setMauSac(mauSac);
        mauxe.setNuocSX(nuocSX);
        mauxe.setMaLoaiXe(maLoaiXe);
        mauxe.setGia(gia);
        mauxe.setSoluong(soLuong);
        mauXeDAO = new MauXeDAO();
        mauXeDAO.themMauXe(mauxe);
        showlistMauXe();
        jDialog_ThemMauXe.dispose();
        
    }//GEN-LAST:event_jButton_themxe_luuMouseClicked

    private void jButton_themChiTietXe_luuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_themChiTietXe_luuMouseClicked
        // TODO add your handling code here:
        String soKhung = jTextField_themChiTietXe_SoKhung.getText();
        String soMay = jTextField_themChiTietXe_SoMay.getText();
        String tenmauxe = jComboBox_TenXe.getSelectedItem().toString();
        mauXeDAO = new MauXeDAO();
        MauXe mauxe = mauXeDAO.getMauXeByName(tenmauxe);
        int maMauXe = mauxe.getMaMauXe();
        
        Xe xe = new Xe();
        xe.setMaMauXe(maMauXe);
        xe.setSoKhung(soKhung);
        xe.setSoMay(soMay);
        xeDAO.themXe(xe);
        showListXe();
        jDialog_ThemChiTietXe.dispose();
        
        
        
    }//GEN-LAST:event_jButton_themChiTietXe_luuMouseClicked

    private void jComboBox_TenXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_TenXeActionPerformed
        // TODO add your handling code here:
        String tenloaixe = jComboBox_TenXe.getSelectedItem().toString();     
        ArrayList<MauXe> mauSacXes = mauXeDAO.getListMauSacXeByName(tenloaixe);
        Vector<String> dataMauSacXe = new Vector();
        mauSacXes.forEach((mausacxe)->{
            dataMauSacXe.add(mausacxe.getMauSac());
        });
        DefaultComboBoxModel modelMauSacXe = new DefaultComboBoxModel(dataMauSacXe);
        jComboBox_mauSac.setModel(modelMauSacXe);
    }//GEN-LAST:event_jComboBox_TenXeActionPerformed

    private void jTable_dsMauXeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_dsMauXeMouseClicked
        // TODO add your handling code here:
        showListXe();
    }//GEN-LAST:event_jTable_dsMauXeMouseClicked

    private void jButton_xoa_xe_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_xoa_xe_MouseClicked
        // TODO add your handling code here:
           try {
            int r = this.jTable_ds_ChitietXe.getSelectedRow();
            if (r == -1) {
                JOptionPane.showMessageDialog(null, "Bạn Phải Chọn Xe Cần Xóa");
            } else {
                int result = JOptionPane.showConfirmDialog(null, "Bạn Có Muốn Xóa xe này", "Xóa Xe", JOptionPane.YES_NO_OPTION);

                if (result == JOptionPane.YES_OPTION) {

                    String xe = this.jTable_ds_ChitietXe.getValueAt(r, 0).toString();
                    if (xeDAO.deleteXe(Integer.parseInt(xe))) {
                        JOptionPane.showMessageDialog(null, "Xóa Xe Thành Công!!");
                        
                    } else {
                        JOptionPane.showMessageDialog(null, "Lỗi");
                    }
                }
            }
        } catch (Exception e) {
            
        }
        showListXe();
    }//GEN-LAST:event_jButton_xoa_xe_MouseClicked

    
     private void setComBoModel() {
        // ComboBox Loại Xe
        LoaiXeDAO tenLoaiXeDAO = new LoaiXeDAO();
        ArrayList<LoaiXe> listTenLoaiXe = tenLoaiXeDAO.getListTenLoaiXe();
        Vector<String> dataTenLoaiXe = new Vector();
        
        listTenLoaiXe.forEach((tenloaixe)->{
           dataTenLoaiXe.add(tenloaixe.getTenLoaiXe()); 
        });
        DefaultComboBoxModel modelLoaiXe = new DefaultComboBoxModel(dataTenLoaiXe);
        jComboBox_LoaiXe.setModel(modelLoaiXe);
        
       // ComboBox Tên Xe
        mauXeDAO = new MauXeDAO();
        ArrayList<MauXe> tenMauXes = mauXeDAO.getListTenMauXe();
        Vector<String> dataTenMauXe = new Vector();
        tenMauXes.forEach((tenmauxe)->{
            dataTenMauXe.add(tenmauxe.getTenMauXe());
        });
        DefaultComboBoxModel modelMauXe = new DefaultComboBoxModel(dataTenMauXe);
        jComboBox_TenXe.setModel(modelMauXe);
 
    }
     

     
      private void showlistMauXe() {
        Vector vData = new Vector();
        Vector vColumn = new Vector();
        mauXeDAO = new MauXeDAO();
        loaiXeDAO = new LoaiXeDAO();
        listMauXe=mauXeDAO.getListMauXe();
        vColumn.removeAllElements();
        vColumn.add("Tên Mẫu Xe");
        vColumn.add("Tên Loại Xe");
    
        vColumn.add("Nước Sản Xuất");
        vColumn.add("Màu Sắc");
        vColumn.add("Giá");
        vColumn.add("Số Lượng");
        for (int i = 0; i < listMauXe.size(); i++) {
            Vector vRow = new Vector();
            MauXe mauxe =  listMauXe.get(i);
          
            vRow.add(mauxe.getTenMauXe());
            
            LoaiXe loaiXe = loaiXeDAO.getLoaiXeByID(mauxe.getMaLoaiXe());
            vRow.add(loaiXe.getTenLoaiXe());
            
            vRow.add(mauxe.getNuocSX());
            vRow.add(mauxe.getMauSac());
            vRow.add(mauxe.getGia());
            vRow.add(mauxe.getSoluong());
            vData.add(vRow);
        }
        DefaultTableModel model = new DefaultTableModel(vData, vColumn);
        jTable_dsMauXe.setModel(model);
    }
    
    private void showListXe() {
        Vector vData = new Vector();
        Vector vColumn = new Vector();
        vColumn.removeAllElements();
        vColumn.add("Mã Xe");
        vColumn.add("Số Khung");
        vColumn.add("Số Máy");
        vColumn.add("Mã Mẫu Xe");
        vColumn.add("Màu Sắc");
        
        try{
            int r = jTable_dsMauXe.getSelectedRow();
            if (r != -1) {
                mauXeDAO = new MauXeDAO();
                
                String maMauXe = jTable_dsMauXe.getValueAt(r, 0).toString();
                listXe = xeDAO.getListXeBymaMauXe(Integer.parseInt(maMauXe));
                
                for (int i = 0; i < listXe.size(); i++) {
                    Vector vRow = new Vector();
                    Xe xe =  listXe.get(i);
                    vRow.add(xe.getMaXe());
                    vRow.add(xe.getSoKhung());
                    vRow.add(xe.getSoMay());
                    vRow.add(xe.getMaMauXe());
                    
                    MauXe mauXe = mauXeDAO.getMauXeById(xe.getMaMauXe());
                    vRow.add(mauXe.getMauSac());
                    
                
                    
                   
                    vData.add(vRow);
                }   
            }
        }catch(Exception e){    
        }
        DefaultTableModel model = new DefaultTableModel(vData, vColumn);
        jTable_ds_ChitietXe.setModel(model);
    }
   
      

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_sua_xe_;
    private javax.swing.JButton jButton_suaxe_huy_;
    private javax.swing.JButton jButton_themChiTietXe_huy;
    private javax.swing.JButton jButton_themChiTietXe_luu;
    private javax.swing.JButton jButton_them_chitietxe_;
    private javax.swing.JButton jButton_them_mauxe_;
    private javax.swing.JButton jButton_themxe_huy_;
    private javax.swing.JButton jButton_themxe_luu;
    private javax.swing.JButton jButton_themxe_luu1;
    private javax.swing.JButton jButton_tim_xe_;
    private javax.swing.JButton jButton_xoa_xe_;
    private javax.swing.JComboBox<String> jComboBox_LoaiXe;
    private javax.swing.JComboBox<String> jComboBox_TenXe;
    private javax.swing.JComboBox<String> jComboBox_mauSac;
    private javax.swing.JDialog jDialog_SuaXe;
    private javax.swing.JDialog jDialog_ThemChiTietXe;
    private javax.swing.JDialog jDialog_ThemMauXe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable_dsMauXe;
    private javax.swing.JTable jTable_ds_ChitietXe;
    private javax.swing.JTextField jTextField_suaXe_soluong;
    private javax.swing.JTextField jTextField_suaXe_tenxe;
    private javax.swing.JTextField jTextField_suaxe_gia;
    private javax.swing.JTextField jTextField_suaxe_loaixe;
    private javax.swing.JTextField jTextField_suaxe_mausac;
    private javax.swing.JTextField jTextField_suaxe_nuocsx;
    private javax.swing.JTextField jTextField_suaxe_sokhung;
    private javax.swing.JTextField jTextField_suaxe_somay;
    private javax.swing.JTextField jTextField_themChiTietXe_SoKhung;
    private javax.swing.JTextField jTextField_themChiTietXe_SoMay;
    private javax.swing.JTextField jTextField_themXe_soluong;
    private javax.swing.JTextField jTextField_themXe_tenxe;
    private javax.swing.JTextField jTextField_themxe_gia;
    private javax.swing.JTextField jTextField_themxe_mausac;
    private javax.swing.JTextField jTextField_themxe_nuocsx;
    private javax.swing.JTextField jTextField_tim_xe_;
    // End of variables declaration//GEN-END:variables

    
}
